foodieFinal/accounts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(
        r'^users/$',
        views.ListAccountView.as_view(),
        name='user_list'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/$',
        views.DetailAccountView.as_view(),
        name='profile'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/update/$',
        views.UpdateAccountView.as_view(),
        name='update'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/update/password/$',
        views.ChangePasswordView.as_view(),
        name='change_password'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/followers$',
        views.FollowersListView.as_view(),
        name='followers'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/following/$',
        views.FollowingListView.as_view(),
        name='following'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/follow/$',
        views.follow_view,
        name='follow'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/unfollow/$',
        views.unfollow_view,
        name='unfollow'
    ),
]

foodieFinal/foodie/urls.py
from __future__ import absolute_import

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^u/', include('accounts.urls', namespace='accounts')),
    url(r'^p/', include('posts.urls', namespace='posts')),
    url(r'^e', include('explore.urls', namespace='explore')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodieFinal/posts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'create/$',
        views.CreatePostView.as_view(),
        name='create'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/$',
        views.DetailPostView.as_view(),
        name='view'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/update/$',
        views.UpdatePostView.as_view(),
        name='update'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/delete/$',
        views.DeletePostView.as_view(),
        name='delete'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/like/$',
        views.like_post_view,
        name='like'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/unlike/$',
        views.unlike_post_view,
        name='unlike'
    ),
    url(r'(?P<slug>[\w\-]{10})/dislike/$',
        views.dislike_post_view,
        name = 'dislike'
    ),
    url(r'(?P<slug>[\w\-]{10})/undislike/$',
        views.undislike_post_view,
        name = 'undislike'
    ),
    url(r'(?P<slug>[\w\-]{10})/comment/$',
        views.comment_post_view,
        name = 'comment'
    )

]

foodieFinal/posts/models.py
import string as str
from random import choice

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible

from accounts.models import User


def generate_id():
        n = 10
        random = str.ascii_uppercase + str.ascii_lowercase + str.digits
        return ''.join(choice(random) for _ in range(n))


@python_2_unicode_compatible
class Post(models.Model):
    author = models.ForeignKey(User, related_name='post')
    slug = models.SlugField(unique=True, max_length=10, default=generate_id)
    photo = models.FileField(upload_to='posts_photo')
    caption = models.CharField(max_length=50, blank=True)
    location = models.CharField(max_length = 255, blank = True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Posts'
        ordering = ['-date_created', ]

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('posts:view', kwargs={'slug': self.slug})


@python_2_unicode_compatible
class Like(models.Model):
    post = models.ForeignKey(Post, related_name='liked_post')
    user = models.ForeignKey(User, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post

@python_2_unicode_compatible
class Dislike(models.Model):
    post = models.ForeignKey(Post, related_name = 'disliked_post')
    user = models.ForeignKey(User, related_name = 'disliker')

    def __str__(self):
        return self.post


@python_2_unicode_compatible
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name = 'commented_post')
    commentor = models.ForeignKey(User, related_name = 'commentor')
    text = models.CharField(max_length = 255)

    def __str__(self):
        return '{}:{}:{}'.format(self.post, self.commentor, self.text)

foodieFinal/posts/forms.py
from __future__ import absolute_import

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

from .models import Post


class UpdatePostForm(forms.ModelForm):
    class Meta:
        fields = ('caption', 'location', )
        model = Post

    def __init__(self, *args, **kwargs):
        super(UpdatePostForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'caption',
            'location',
            Submit('update', 'Update', css_class='btn primary')
        )


class CreatePostForm(forms.ModelForm):
    class Meta:
        fields = ('photo', 'caption', 'location',)
        model = Post

    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'photo',
            'caption',
            'location',
            Submit('post', 'Post', css_class='btn primary')
        )

foodieFinal/posts/views.py
from __future__ import absolute_import

from django.contrib.auth.decorators import login_required
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.http import HttpResponseRedirect

from braces import views

from .models import Post, Like, Dislike, Comment
from .forms import CreatePostForm, UpdatePostForm
from .helpers import get_post


class DetailPostView(
        views.LoginRequiredMixin,
        generic.DetailView
):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(DetailPostView, self).get_context_data(**kwargs)
        context['post'] = get_post(self.kwargs['slug'])
        context['dislike'] = Dislike.objects.all()
        context['comment'] = Comment.objects.all()
        return context


class CreatePostView(
        views.LoginRequiredMixin,
        generic.CreateView
):
    model = Post
    form_class = CreatePostForm
    template_name = 'posts/post_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super(CreatePostView, self).form_valid(form)


class UpdatePostView(
        views.LoginRequiredMixin,
        views.FormValidMessageMixin,
        generic.UpdateView
):
    model = Post
    form_valid_message = 'Successfully updated your post.'
    form_class = UpdatePostForm
    template_name = 'posts/post_form.html'

    def get(self, request, *args, **kwargs):
        post = Post.objects.get(slug=kwargs['slug'])

        if (post.author != request.user):
            messages.warning(
                request,
                'You don\'t have permission to update this post.',
            )
            return HttpResponseRedirect(
                reverse_lazy(
                    'posts:view',
                    kwargs={'slug': kwargs['slug']}
                )
            )
        else:
            return super(UpdatePostView, self).get(request, *args, **kwargs)


class DeletePostView(
        views.LoginRequiredMixin,
        views.FormValidMessageMixin,
        generic.DeleteView
):
    model = Post
    form_valid_message = 'Successfully deleted your post.'
    success_url = reverse_lazy('home')
    template_name = 'posts/post_delete.html'

    def get(self, request, *args, **kwargs):
        post = Post.objects.get(slug=kwargs['slug'])

        if (post.author != request.user):
            messages.warning(
                request,
                'You don\'t have permission to delete this post.',
            )
            return HttpResponseRedirect(
                reverse_lazy(
                    'posts:view',
                    kwargs={'slug': kwargs['slug']}
                )
            )
        else:
            return super(DeletePostView, self).get(request, *args, **kwargs)


@login_required
def like_post_view(request, *args, **kwargs):
    try:
        post = Post.objects.get(slug=kwargs['slug'])

        _, created = Like.objects.get_or_create(post=post, user=request.user)

        try:
            dislike = Dislike.objects.get(
            post__slug=kwargs['slug'],
            user=request.user
        )
            if dislike:
                dislike.delete()
        except:
            pass

        else:
            messages.warning(request, 'You liked the post')

        if not created:
            messages.warning(
                request,
                'You\'ve already liked the post.'
            )
    except Post.DoesNotExist:
        messages.warning(
            request,
            'Post does not exist'
        )

    return HttpResponseRedirect(
        reverse_lazy(
            'posts:view',
            kwargs={'slug': kwargs['slug']}
        )
    )


@login_required
def unlike_post_view(request, *args, **kwargs):
    try:
        like = Like.objects.get(
            post__slug=kwargs['slug'],
            user=request.user
        )
    except Like.DoesNotExist:
        messages.warning(
            request,
            'You didn\'t like the post.'
        )
    else:
        like.delete()

    return HttpResponseRedirect(
        reverse_lazy(
            'posts:view',
            kwargs={'slug': kwargs['slug']}
        )
    )

@login_required
def dislike_post_view(request, *args, **kwargs):
    try:
        post = Post.objects.get(slug = kwargs['slug'])

        _, created = Dislike.objects.get_or_create(post = post, user = request.user)

        try:
            like = Like.objects.get(
            post__slug=kwargs['slug'],
            user=request.user
        )

            if like:
                like.delete()
        except:
            pass 
        else:
            messages.warning(request, 'You disliked the post')

        if not created:
            messages.warning(request, 'You\'ve already disliked the post.')
    except Post.DoesNotExist:
        messages.warning(request, 'Post does not exist!')

    return HttpResponseRedirect(reverse_lazy('posts:view', kwargs = {'slug':kwargs['slug']}))

@login_required
def undislike_post_view(request, *args, **kwargs):
    try:
        dislike = Dislike.objects.get(
            post__slug = kwargs['slug'],
            user = request.user
        )
    except Dislike.DoesNotExist:
        messages.warning(
            requeust,
            'You did\'t dislike the post.'
        )
    else:
        dislike.delete()

    return HttpResponseRedirect(
        reverse_lazy(
            'posts:view',
            kwargs={'slug': kwargs['slug']}
        )
    )

@login_required
def comment_post_view(request, *args, **kwargs):
    if request.method == 'POST':
        try:
            post = Post.objects.get(slug = kwargs['slug'])
            text = request.POST.get('comment')
            if text != '':
                _, created = Comment.objects.get_or_create(post = post, commentor = request.user, text = text)

                if not created:
                    messages.warning(request, 'Something went wrong.Please Try again')
            else:
                messages.warning(request, 'You can\'t post blank comments')

        except Post.DoesNotExist:
            messages.warning(request, 'Post does not exist')

        return HttpResponseRedirect(reverse_lazy('posts:view', kwargs= {'slug':kwargs['slug']}))

    else:
        return HttpResponseRedirect('/')

foodieFinal/posts/templates/posts/dislikers.html
<div class="modal fade" id="{{ post.slug }}_dislikers_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Dislikes</h4>
            </div>
            <div class="modal-body">
                {% for x in dislike %}
                    {% if x.post == post%}
                        <a href="{% url 'accounts:profile' x.user %}"><h1>{{ x.user }}</h1></a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

foodieFinal/posts/templates/posts/likers.html
<div class="modal fade" id="{{ post.slug }}_likers_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Likers</h4>
            </div>
            <div class="modal-body">
                {% for liker in post.liker %}
                    <a href="{% url 'accounts:profile' liker.username %}"><h1>{{ liker.username }}</h1></a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

foodieFinal/posts/templates/posts/post.html
</br>
<div id="{{ post.slug }}">
    <div class="post">
    </br>
        <div class = "userinfo"><a href="{{ post.author.get_absolute_url }}"><b>{{ post.author }}</b></a> </br>
            {% if post.location %}
            <i class="fas fa-map-marker-alt"></i><address>{{post.location}}</address>
            {% endif %}
        </br>
        {% if user ==  post.author %}
        </div>
            | <a href = "{% url 'posts:update' post.slug %}">Update</a> |
            <a href = "{% url 'posts:delete' post.slug %}">Delete</a> |
        {% endif %}
        <img src="{{ post.photo.url }}" alt="{{ post.caption }}" width="660px" height="450px" class="responsive"/></br></br>
        <p>{{ post.caption }}</p>
  <div class ="posttime">  <a href="{% url 'posts:view' post.slug %}">{{ post.date_created }}</a></div>
  <hr>
     <div class="panel-footer foot">
            <b><a href="#" data-toggle="modal" data-target="#{{ post.slug }}_likers_modal">Likes : {{ post.liker|length }}</a></b>
            {% include 'posts/likers.html' %}&nbsp;
       <b><a href="#" data-toggle = "modal" data-target = "#{{ post.slug }}_dislikers_modal">Dislikes : {{dislikes|length}}</a></b>
            {% include 'posts/dislikers.html' %} &nbsp;
        <div class="input-group">
            {% if user in post.liker %}
                <a href="{% url 'posts:unlike' post.slug %}" class="input-group-addon btn btn-default blue"><i class="fas fa-thumbs-up"></i></a>
            {% else %}
                <a href="{% url 'posts:like' post.slug %}" class="input-group-addon btn btn-default"><i class="far fa-thumbs-up"></i></a>
            {% endif %}
                {% if user in dislike and post in dislike %}
                        <a href="{% url 'posts:undislike' post.slug %}" class = "input-grooup-addon btn btn-default blue"><i class = "fas fa-thumbs-down"></i></a>
                {% else %}
                <a href="{% url 'posts:dislike' post.slug %}" class = "input-group-addon btn btn-default"><i class = "far fa-thumbs-down"></i></a>
                {% endif %}
                <form name = "commentform" action="{% url 'posts:comment' post.slug %}" method="post">
                    {% csrf_token %}
                  &nbsp;  <input class="cmnt" type="text" name = "comment" size="42%" placeholder="Add a Comment..." aria-describedby="comment">
                  <input class = "btn btn-primary" type="submit" name="submit" value = "Comment">
                </form>
        </div>
      </br>
        {% for z in comment %}
            {% if z.post == post %}
                <a href = "{{post.author.get_absolute_url}}"><b>{{z.commentor}}</b></a> : {{z.text}}</br></br>
            {% endif %}
        {% endfor %}
    </div>
</div></div>
<script type="text/javascript">
    $(document).ready(function () {
    //Convert address tags to google map links - Copyright Michael Jasper 2011
    $('address').each(function () {
        var link = "<a href='http://maps.google.com/maps?q=" + encodeURIComponent( $(this).text() ) + "' target='_blank'>" + $(this).text() + "</a>";
        $(this).html(link);
    });
});
</script>

foodieFinal/posts/templates/posts/post_delete.html
{% extends 'base.html' %}

{% block content %}</br>
    <img src="{{ post.photo.url }}" alt="{{ post.caption.url }}" class="responsive">
  </br></br>
    <p><b>{{ post.caption }}</b></p>
    <form action="" method="post">
        {% csrf_token %}
        <p><b>Are you sure you want to delete this post?</b></p>
        <input type="submit" name="yes" value="Yes" class="btn btn-success" />
        <a href="{% url 'posts:view' post %}" class="btn btn-danger">Cancel</a>
    </form>
{% endblock %}

foodieFinal/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.author.name }} Foodie: "{{ post.caption }}"{% endblock %}

{% block content %}
    {% include 'posts/post.html' %}
{% endblock %}

foodieFinal/posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    {% crispy form %}
{% endblock %}