foodieFinal/explore/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views

urlpatterns = [
	url(
			r'',views.explore_post_view, name = 'explore'
	)
]

foodieFinal/foodie/urls.py
from __future__ import absolute_import

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^u/', include('accounts.urls', namespace='accounts')),
    url(r'^p/', include('posts.urls', namespace='posts')),
    url(r'^e', include('explore.urls', namespace='explore')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodieFinal/posts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'create/$',
        views.CreatePostView.as_view(),
        name='create'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/$',
        views.DetailPostView.as_view(),
        name='view'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/update/$',
        views.UpdatePostView.as_view(),
        name='update'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/delete/$',
        views.DeletePostView.as_view(),
        name='delete'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/like/$',
        views.like_post_view,
        name='like'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/unlike/$',
        views.unlike_post_view,
        name='unlike'
    ),
    url(r'(?P<slug>[\w\-]{10})/dislike/$',
        views.dislike_post_view,
        name = 'dislike'
    ),
    url(r'(?P<slug>[\w\-]{10})/undislike/$',
        views.undislike_post_view,
        name = 'undislike'
    ),
    url(r'(?P<slug>[\w\-]{10})/comment/$',
        views.comment_post_view,
        name = 'comment'
    )

]

foodieFinal/explore/models.py
from django.db import models
from posts import models as pm

# Create your models here.

class Rating(models.Model):
	post = models.ForeignKey(pm.Post, unique = True)
	rate = models.IntegerField(default = 10)

	def __str__(self):
		return '{}:{}'.format(self.post, self.rate)

	class Meta:
		ordering = ['-rate']

foodieFinal/explore/views.py
from django.shortcuts import render
from posts import models as pm
from . import models as rm 
# Create your views here.

def explore_post_view(request):
	path = 'explore/explore.html'
	ratings = rm.Rating.objects.all()
	posts = pm.Post.objects.all()
	var = {
		'ratings':ratings,
		'posts':posts
	}
	return render(request, path, var)

foodieFinal/explore/templates/explore/explore.html
{% extends 'base.html' %}

{% block content %}
	{% for x in ratings %}
		{% if x.post in posts %}
		<br>
		<div id = "{{post.slug}}">
		<div class = "post">
		</br>
			<div class = "userinfo"><a href="{{x.post.author.get_absolute_url }}"><b>@{{x.post.author}}</b></a>
				{% if post.location %}
     <i class="fas fa-map-marker-alt"></i><address>{{post.location}}</address>
    {% endif %}
			<img src="{{x.post.photo.url}}" width = "660px" height="450px" class = "responsive"><br>
		</div><br>
		<div class = "posttime panel-footer"><a href="{% url 'posts:view' x.post.slug %}">{{x.post.date_created}}</a><p class = "text-right">
	Rating : {{x.rate}}%
</p></div>
</div>
		{% endif %}
	{% endfor %}
{% endblock %}