foodieFinal/accounts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(
        r'^users/$',
        views.ListAccountView.as_view(),
        name='user_list'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/$',
        views.DetailAccountView.as_view(),
        name='profile'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/update/$',
        views.UpdateAccountView.as_view(),
        name='update'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/update/password/$',
        views.ChangePasswordView.as_view(),
        name='change_password'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/followers$',
        views.FollowersListView.as_view(),
        name='followers'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/following/$',
        views.FollowingListView.as_view(),
        name='following'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/follow/$',
        views.follow_view,
        name='follow'
    ),
    url(
        r'^(?P<username>[-\w]{5,30})/unfollow/$',
        views.unfollow_view,
        name='unfollow'
    ),
]

foodieFinal/explore/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views

urlpatterns = [
	url(
			r'',views.explore_post_view, name = 'explore'
	)
]

foodieFinal/foodie/urls.py
from __future__ import absolute_import

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^u/', include('accounts.urls', namespace='accounts')),
    url(r'^p/', include('posts.urls', namespace='posts')),
    url(r'^e', include('explore.urls', namespace='explore')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodieFinal/posts/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'create/$',
        views.CreatePostView.as_view(),
        name='create'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/$',
        views.DetailPostView.as_view(),
        name='view'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/update/$',
        views.UpdatePostView.as_view(),
        name='update'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/delete/$',
        views.DeletePostView.as_view(),
        name='delete'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/like/$',
        views.like_post_view,
        name='like'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/unlike/$',
        views.unlike_post_view,
        name='unlike'
    ),
    url(r'(?P<slug>[\w\-]{10})/dislike/$',
        views.dislike_post_view,
        name = 'dislike'
    ),
    url(r'(?P<slug>[\w\-]{10})/undislike/$',
        views.undislike_post_view,
        name = 'undislike'
    ),
    url(r'(?P<slug>[\w\-]{10})/comment/$',
        views.comment_post_view,
        name = 'comment'
    )

]

foodieFinal/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Foodie{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href='https://www.w3schools.com/w3css/4/w3.css' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <script  src="{% static 'assets/js/animate.js' %}"></script>
    <style>
        body {
            padding-bottom: 20px;
            padding-top: 70px;
        }
        .messages {
            list-style: none;
        }
        .blue, .blue:hover, .blue:visited,
        .blue:active, .blue:focus, .blue:link {
            color: #0078D7;
        }
    </style>
    {% block css %}{% endblock css %}
</head>
<body onload="animate()">
    <nav class="navbar navbar-default navbar-fixed-top customnavbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand logo" href="{% url 'home' %}"><img src = "{% static 'img/logo.png'%}"></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{{ user.get_absolute_url }}">{{ user.username }}</a></li>
                        <li><a href="{% url 'posts:create' %}">Create Post</a></li>
                        <li><a href="{% url 'accounts:user_list' %}">List of Users</a></li>
                        <li><a href="{%url 'explore:explore' %}">Explore</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">SignUp</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h1>{% block headline %}{% endblock headline %}</h1>

        {% block content %}{% endblock content %}
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock js %}
</body>
</html>

foodieFinal/templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        {% for post in posts  %}
            {% include 'posts/post.html' %}
        {% endfor %}
    {% else %}
    <div class="pointer">
      <a href="http://www.animatedimages.org/cat-arrows-111.htm"><img src="http://www.animatedimages.org/data/media/111/animated-arrow-image-0044.gif" border="0" alt="animated-arrow-image-0044" /></a>
    </div>
      <div class="moving-letters">
          <h1 class="ml6">
          <span class="text-wrapper">
              <span class="letters">Welcome to FOODIE Community ! </span>
          </span>
          </h1>
          </div>
          <div class="w3-animate-zoom image">
           <div class = "chickenimage"><img src="../static/img/chicken.jpg" alt="Foodie"/></div>
           <div class = "burgerimage"><img src="../static/img/burger.jpg" alt="Foodie"/></div>
           <div class = "pizzaimage"><img src="../static/img/Pizza.jpg" alt="Foodie"/></div>
          </div>
  {% endif %}
{% endblock %}